-- Minimal stand-ins for the Supabase primitives the security migrations expect,
-- so both can be applied verbatim to a throwaway local cluster.
--
-- These stubs deliberately supply IDENTITY and STRUCTURE only. Every role rule
-- under test — `mb_current_user_role`, `mb_can_read_module`, the RLS policies,
-- the grants — comes from the real migration files, never from here. Stubbing
-- those would make the tests agree with themselves rather than with production.

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        CREATE ROLE anon NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        CREATE ROLE authenticated NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'service_role') THEN
        CREATE ROLE service_role NOLOGIN BYPASSRLS;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'supabase_auth_admin') THEN
        CREATE ROLE supabase_auth_admin NOLOGIN;
    END IF;
END $$;

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

-- ── auth ────────────────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS auth;
-- `handle_new_user` reads `raw_user_meta_data` off the inserted row, so the
-- column has to be here for the invitation trigger to fire realistically.
CREATE TABLE IF NOT EXISTS auth.users (
    id uuid PRIMARY KEY,
    email text,
    raw_user_meta_data jsonb NOT NULL DEFAULT '{}'::jsonb
);

/*
 * The signed-in user, taken from a session GUC so a test can act as anyone.
 * In Supabase this reads the JWT claim; the shape returned is identical, which
 * is all the policies depend on.
 */
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid
LANGUAGE sql STABLE AS $$
    SELECT NULLIF(current_setting('test.uid', true), '')::uuid;
$$;
GRANT USAGE ON SCHEMA auth TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION auth.uid() TO anon, authenticated, service_role;

-- ── storage ─────────────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS storage;
CREATE TABLE IF NOT EXISTS storage.buckets (
    id text PRIMARY KEY,
    name text,
    public boolean NOT NULL DEFAULT false
);
CREATE TABLE IF NOT EXISTS storage.objects (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    bucket_id text NOT NULL,
    name text NOT NULL,
    owner uuid
);

/* Supabase splits an object path on "/" to derive its folder segments; the
 * avatar and Grafana policies compare segment 1 against the caller's uid. */
CREATE OR REPLACE FUNCTION storage.foldername(name text) RETURNS text[]
LANGUAGE sql IMMUTABLE AS $$
    SELECT string_to_array(name, '/');
$$;

INSERT INTO storage.buckets (id, name, public) VALUES
    ('avatars', 'avatars', true),
    ('grafana-uploads', 'grafana-uploads', true)
    ON CONFLICT (id) DO NOTHING;

GRANT USAGE ON SCHEMA storage TO anon, authenticated, service_role;

-- ── the profile/role source of truth ────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text,
    full_name text,
    avatar_url text,
    role text NOT NULL DEFAULT 'viewer'
);

-- ── the core tables the migration's preflight requires, plus one table per
--    module the RLS tests exercise. Columns are illustrative: the policies
--    under test gate ROWS, not columns.
CREATE TABLE IF NOT EXISTS public.water_meters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label text,
    account_number text
);
CREATE TABLE IF NOT EXISTS public.water_monthly_consumption (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_id bigint,
    month text,
    consumption numeric
);
CREATE TABLE IF NOT EXISTS public.electricity_meters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text
);
CREATE TABLE IF NOT EXISTS public.electricity_readings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meter_id bigint,
    reading numeric
);
CREATE TABLE IF NOT EXISTS public.stp_operations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date date,
    inlet_sewage numeric,
    tse_for_irrigation numeric,
    tanker_trips numeric
);
CREATE TABLE IF NOT EXISTS public.amc_register (
    agreement_id text PRIMARY KEY,
    contractor text,
    service_system text,
    end_date date
);
-- Mirrors the review columns in sql/migrations/create_professional_applications.sql.
-- The intake policy references them directly and, unlike the neighbouring
-- contractor_contracts block, does not guard on their existence — so a stub
-- missing them aborts the whole migration, exactly as a live table would.
CREATE TABLE IF NOT EXISTS public.professional_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text,
    status text DEFAULT 'pending',
    reviewer_notes text,
    reviewed_by uuid REFERENCES auth.users(id),
    reviewed_at timestamptz
);
