import React, { useState, useEffect, useMemo, useRef } from 'react';
import {
  Chart as ChartJS, ArcElement, Tooltip as ChartTooltip, Legend,
  CategoryScale, LinearScale, BarElement, Title, Chart,
  ChartOptions
} from 'chart.js';
import { Pie, Bar } from 'react-chartjs-2';
import {
  Landmark, Search, Bell, UserCircle, LayoutDashboard, Calculator,
  Building2, Play, Globe2, MapPin, Ruler, Banknote, Scale
} from 'lucide-react';

// Register Chart.js components needed
ChartJS.register(ArcElement, ChartTooltip, Legend, CategoryScale, LinearScale, BarElement, Title);

// --- DATA ---
const rates = {
  zone: {
    "Zaha": 0.439,
    "Nameer": 1.098,
    "Wajd": 0.329,
    "C Sector": 1.756, // Using Master Community rate as zone rate for Commercial
    "FM": 3.952
  },
  masterCommunity: 1.914, // Derived rate based on user's list total area
};

// --- FULL PROPERTY DATABASE ---
// Note: Corrected Z3 008 area, handled invalid areas for Z3 056(3B)/Z3 056(4B) -> null
// Note: Staff Accommodation (FM) units included but have null BUA
const propertyDatabase = [
    { unitNo: "Z3 061(1A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 054(4A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z8 007", sector: "Wajd", type: "Villa", unitType: "5 Bed Wajd Villa", bua: 750.35 },
    { unitNo: "3C", sector: "C Sector", type: "Commercial", unitType: "Development Land", bua: 5656.00 },
    { unitNo: "Z3 057(5)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 355.07 },
    { unitNo: "Z5 008", sector: "Nameer", type: "Villa", unitType: "4 Bed Nameer Villa", bua: 497.62 },
    { unitNo: "Z3 050(1)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 019", sector: "Zaha", type: "Villa", unitType: "3 Bed Zaha Villa", bua: 357.12 },
    { unitNo: "Z5 007", sector: "Nameer", type: "Villa", unitType: "3 Bed Nameer Villa", bua: 426.78 },
    { unitNo: "Z3 039", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 045(1)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 029", sector: "Zaha", type: "Villa", unitType: "3 Bed Zaha Villa", bua: 357.12 },
    { unitNo: "Z3 046(1)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 059(1B)", sector: "Zaha", type: "Apartment", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 009", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 010", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 048(2)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 059(3A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 011", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 056(4A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 053(4B)", sector: "Zaha", type: "Apartment", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 054(4B)", sector: "Zaha", type: "Apartment", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 055(1A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 060(3A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 057(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z3 058(3A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 059(1A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 017", sector: "Zaha", type: "Villa", unitType: "3 Bed Zaha Villa", bua: 357.12 },
    { unitNo: "Z3 059(3B)", sector: "Zaha", type: "Apartment", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 061(3A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 060(1A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 022", sector: "Zaha", type: "Villa", unitType: "3 Bed Zaha Villa", bua: 357.12 },
    { unitNo: "Z3 002", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 062(2)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 061(2B)", sector: "Zaha", type: "Apartment", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 075(2)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 033", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 036", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z5 019", sector: "Nameer", type: "Villa", unitType: "4 Bed Nameer Villa", bua: 497.62 },
    { unitNo: "Z5 018", sector: "Nameer", type: "Villa", unitType: "4 Bed Nameer Villa", bua: 497.62 },
    { unitNo: "Z5 020", sector: "Nameer", type: "Villa", unitType: "4 Bed Nameer Villa", bua: 497.62 },
    { unitNo: "Z3 040", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z8 002", sector: "Wajd", type: "Villa", unitType: "5 Bed Wajd Villa", bua: 750.35 },
    { unitNo: "Z5 004", sector: "Nameer", type: "Villa", unitType: "3 Bed Nameer Villa", bua: 426.78 },
    { unitNo: "Z5 009", sector: "Nameer", type: "Villa", unitType: "3 Bed Nameer Villa", bua: 426.78 },
    { unitNo: "Z3 012", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 008", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 }, // Corrected area
    { unitNo: "Z3 055(2B)", sector: "Zaha", type: "Apartment", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 003", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 004", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 058(4A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 013", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 014", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 015", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 020", sector: "Zaha", type: "Villa", unitType: "3 Bed Zaha Villa", bua: 357.12 },
    { unitNo: "Z3 021", sector: "Zaha", type: "Villa", unitType: "3 Bed Zaha Villa", bua: 357.12 },
    { unitNo: "Z3 023", sector: "Zaha", type: "Villa", unitType: "3 Bed Zaha Villa", bua: 357.12 },
    { unitNo: "Z3 030", sector: "Zaha", type: "Villa", unitType: "3 Bed Zaha Villa", bua: 357.12 },
    { unitNo: "Z3 031", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 048(1)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 060(4A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 037", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 038", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 049(1)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 041", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 042", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 055(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z3 043", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 044(1)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 044(2)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 044(3)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 044(4)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 044(5)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 355.07 },
    { unitNo: "Z3 050(2)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 044(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z3 045(2)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 045(3)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 045(4)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 045(5)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 355.07 },
    { unitNo: "Z3 045(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z5 002", sector: "Nameer", type: "Villa", unitType: "3 Bed Nameer Villa", bua: 426.78 },
    { unitNo: "Z3 046(2)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 046(3)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 052(2)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 046(4)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 046(5)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 355.07 },
    { unitNo: "Z3 046(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z3 047(2)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 047(3)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 047(4)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 047(5)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 355.07 },
    { unitNo: "Z3 053(1A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 047(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z3 053(2A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 053(2B)", sector: "Zaha", type: "Apartment", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 048(3)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 053(3A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 048(5)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 355.07 },
    { unitNo: "Z3 048(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z3 049(2)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 054(1A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 049(3)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 054(2A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 054(2B)", sector: "Zaha", type: "Apartment", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 049(4)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 049(5)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 355.07 },
    { unitNo: "Z3 049(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z3 050(3)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 050(4)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 050(5)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 355.07 },
    { unitNo: "Z3 055(2A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 050(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z3 005", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 051(1)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 051(2)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 055(3A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 051(4)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 051(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z3 052(1)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 052(3)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 057(1A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 052(4)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 057(2A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 052(5)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 355.07 },
    { unitNo: "Z3 052(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z3 057(4A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 048(4)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 057(4B)", sector: "Zaha", type: "Apartment", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 053(1B)", sector: "Zaha", type: "Apartment", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 053(3B)", sector: "Zaha", type: "Apartment", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 053(4A)", sector: "Zaha", type: "Apartment", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 053(6)", sector: "Zaha", type: "Apartment", unitType: "3 Bed Zaha Apt", bua: 361.42 },
    { unitNo: "Z3 025", sector: "Zaha", type: "Villa", unitType: "3 Bed Zaha Villa", bua: 357.12 },
    { unitNo: "Z3 058(2A)", sector: "Zaha", type: "Villa", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 054(1B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 054(3A)", sector: "Zaha", type: "Villa", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 054(3B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 055(1B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 074(2)", sector: "Zaha", type: "Villa", unitType: "2 Bed Premium Apt", bua: 199.13 },
    { unitNo: "Z3 055(3B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 059(2A)", sector: "Zaha", type: "Villa", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 006", sector: "Zaha", type: "Villa", unitType: "4 Bed Zaha Villa", bua: 422.24 },
    { unitNo: "Z3 055(4A)", sector: "Zaha", type: "Villa", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 055(4B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 057(1B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 059(4A)", sector: "Zaha", type: "Villa", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 057(2B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 057(3A)", sector: "Zaha", type: "Villa", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 057(3B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 060(2A)", sector: "Zaha", type: "Villa", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 058(1B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 058(2B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 061(2A)", sector: "Zaha", type: "Villa", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 058(3B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 059(2B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 061(4A)", sector: "Zaha", type: "Villa", unitType: "2 Bed Small Apt", bua: 115.47 },
    { unitNo: "Z3 058(4B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 058(5)", sector: "Zaha", type: "Villa", unitType: "3 Bed Zaha Apt", bua: 355.07 },
    { unitNo: "Z3 059(4B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 060(1B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 060(2B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 060(3B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 060(4B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z3 060(5)", sector: "Zaha", type: "Villa", unitType: "3 Bed Zaha Apt", bua: 355.07 },
    { unitNo: "Z3 061(1B)", sector: "Zaha", type: "Villa", unitType: "1 Bed Apt", bua: 79.09 },
    { unitNo: "Z
