-- ==============================================================================
-- FINAL FIX: Create Missing Tables for Assets and AMC Contractors
-- Run this script in the Supabase SQL Editor to resolve 404 errors.
-- ==============================================================================

-- 1. Create `mb_assets` table (Missing Assets Table)
-- Based on the schema inferred from `app/entities/asset.ts`
CREATE TABLE IF NOT EXISTS mb_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id TEXT,
    asset_tag TEXT,
    asset_name TEXT,
    asset_description TEXT,
    asset_type TEXT,
    category TEXT,
    sub_category TEXT,
    system_area TEXT,
    location_name TEXT,
    location_tag TEXT,
    floor_area TEXT,
    building TEXT,
    make_brand TEXT,
    model TEXT,
    capacity_size TEXT,
    country_origin TEXT,
    supplier TEXT,
    install_date TEXT, -- Storing as text to match existing patterns, or use DATE
    life_expectancy_years NUMERIC,
    current_age_years NUMERIC,
    erl_years NUMERIC,
    status TEXT DEFAULT 'Active',
    condition TEXT,
    ppm_frequency TEXT,
    is_active TEXT,
    quantity NUMERIC,
    om_volume TEXT,
    responsibility TEXT,
    amc_contractor TEXT,
    floors_served TEXT,
    notes TEXT,
    source_sheet TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for mb_assets
ALTER TABLE mb_assets ENABLE ROW LEVEL SECURITY;

-- Create generous public policy for mb_assets (Read-Only for now, or Read-Write if needed)
DROP POLICY IF EXISTS "Allow public read access on mb_assets" ON mb_assets;
CREATE POLICY "Allow public read access on mb_assets" ON mb_assets FOR SELECT USING (true);


-- 2. Create `amc_contractor_summary` and related tables (If they don't exist)
-- These were found in `app/sql/data/amc-correct-data.sql` but might not have been run.

CREATE TABLE IF NOT EXISTS amc_contractor_summary (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    no INT,
    contractor TEXT NOT NULL,
    service_category TEXT,
    contract_ref TEXT,
    contract_type TEXT,
    start_date TEXT,
    end_date TEXT,
    duration TEXT,
    monthly_fee_omr TEXT,
    annual_fee_omr TEXT,
    total_contract_value_omr TEXT,
    status TEXT,
    alert TEXT,
    document_status TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS amc_contractor_details (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contractor TEXT NOT NULL,
    contract_ref TEXT,
    scope_of_work TEXT,
    ppm_frequency TEXT,
    response_time_emergency TEXT,
    response_time_normal TEXT,
    liquidated_damages TEXT,
    performance_bond TEXT,
    payment_terms TEXT,
    warranty_period TEXT,
    key_exclusions TEXT,
    contact_person TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS amc_contractor_expiry (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contractor TEXT NOT NULL,
    end_date TEXT,
    days_remaining INT,
    renewal_action_required_by TEXT,
    priority TEXT,
    renewal_status TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS amc_contractor_pricing (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contractor TEXT NOT NULL,
    year_1_omr TEXT,
    year_2_omr TEXT,
    year_3_omr TEXT,
    year_4_omr TEXT,
    year_5_omr TEXT,
    total_omr TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for AMC tables
ALTER TABLE amc_contractor_summary ENABLE ROW LEVEL SECURITY;
ALTER TABLE amc_contractor_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE amc_contractor_expiry ENABLE ROW LEVEL SECURITY;
ALTER TABLE amc_contractor_pricing ENABLE ROW LEVEL SECURITY;

-- Create public read policies for AMC tables
DROP POLICY IF EXISTS "Allow public read on amc_contractor_summary" ON amc_contractor_summary;
CREATE POLICY "Allow public read on amc_contractor_summary" ON amc_contractor_summary FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on amc_contractor_details" ON amc_contractor_details;
CREATE POLICY "Allow public read on amc_contractor_details" ON amc_contractor_details FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on amc_contractor_expiry" ON amc_contractor_expiry;
CREATE POLICY "Allow public read on amc_contractor_expiry" ON amc_contractor_expiry FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public read on amc_contractor_pricing" ON amc_contractor_pricing;
CREATE POLICY "Allow public read on amc_contractor_pricing" ON amc_contractor_pricing FOR SELECT USING (true);

-- 3. Insert Sample Data for Assets (Optional - just to have something)
INSERT INTO mb_assets (asset_name, asset_type, location_name, status, quantity)
SELECT 'Main Water Pump 01', 'Pump', 'Zone 1 Pump Room', 'Active', 1
WHERE NOT EXISTS (SELECT 1 FROM mb_assets LIMIT 1);

INSERT INTO mb_assets (asset_name, asset_type, location_name, status, quantity)
SELECT 'Fire Panel Main', 'Fire Safety', 'Control Room', 'Active', 1
WHERE NOT EXISTS (SELECT 1 FROM mb_assets LIMIT 1);
